[package]
name = "cli-grrs"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"]}
anyhow = { version = "1.0" }
clap-verbosity-flag = "2.2.2"
log = "0.4.22"
env_logger = "0.11.5"
